# Generated by Django 3.0 on 2019-12-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
