# Generated by Django 3.0 on 2019-12-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold', '0004_auto_20191219_0057'),
    ]

    operations = [
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
