# Generated by Django 3.0 on 2020-01-08 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold', '0005_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
