# Generated by Django 3.0 on 2020-01-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold', '0006_auto_20200108_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagedb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('file', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'Imagedb',
            },
        ),
    ]
