# Generated by Django 3.0 on 2020-01-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold', '0007_imagedb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.FileField(upload_to='images'),
        ),
    ]
