# Generated by Django 3.0 on 2020-01-11 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gold', '0009_auto_20200110_0224'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
