# Generated by Django 3.0 on 2020-01-12 13:17

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold', '0011_auto_20200112_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200, verbose_name=django.contrib.auth.models.User)),
                ('mobile', models.IntegerField()),
                ('about', models.CharField(max_length=200)),
            ],
        ),
    ]
