# Generated by Django 3.0 on 2020-01-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold', '0014_auto_20200112_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('pincode', models.IntegerField()),
                ('mobile', models.IntegerField()),
                ('city', models.CharField(max_length=200)),
                ('password', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
