# Generated by Django 3.0 on 2020-02-13 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gold', '0016_auto_20200128_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='image',
            new_name='img',
        ),
    ]
