# Generated by Django 3.0 on 2020-02-13 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gold', '0017_auto_20200213_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='img',
            new_name='image',
        ),
    ]
