# Generated by Django 3.0 on 2020-02-17 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gold', '0018_auto_20200213_1850'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
