# Generated by Django 3.0 on 2020-02-17 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gold', '0020_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='slider',
        ),
    ]
