# Generated by Django 3.1.2 on 2020-12-20 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gold', '0022_slider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
    ]
