# Generated by Django 3.1.2 on 2021-01-04 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gold', '0023_delete_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
