# Generated by Django 3.1.2 on 2021-01-04 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gold', '0029_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
    ]
