# Generated by Django 3.1.2 on 2021-01-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold', '0032_user_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_address',
            name='address2',
        ),
        migrations.AddField(
            model_name='user_address',
            name='mobile',
            field=models.IntegerField(default=0),
        ),
    ]
