# Generated by Django 3.1.2 on 2021-01-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold', '0033_auto_20210105_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idd', models.IntegerField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('uname', models.CharField(max_length=150)),
            ],
        ),
    ]
